package com.xenia.ticket.utils.common


enum class CompanyKey(val code: String) {
    CATEGORY_ENABLE("CATEGORY_ENABLE"),
    DEFAULT_LANGUAGE("DEFAULT_LANGUAGE"),
    COMPANY_LANGUAGES("COMPANY_LANGUAGES"),
    COMPANYLOGO_L("COMPANYLOGO_L"),
    COMPANYLOGO_P("COMPANYLOGO_P"),
    COMPANYPRINT_H("COMPANYPRINT_H"),
    COMPANYPRINT_F("COMPANYPRINT_F"),
    ISPAYMENTGATEWAY("ISPAYMENTGATEWAY"),
    PREFIX("PREFIX"),
    PAYMENT_GATEWAY("PAYMENT_GATEWAY"),
    ISPRINTQR("ISPRINTQR"),
    TERMS_AND_CONDITIONS("TERMS_AND_CONDITIONS"),
    ISWHATSAPPENABLED("ISWHATSAPPENABLED"),
    IS_NAME_MANDATORY("IS_NAME_MANDATORY"),

    IS_PHONE_NUMBER_MANDATORY("IS_PHONE_NUMBER_MANDATORY")
}
